openapi: 3.1.0
info:
  title: Gastronomie Pizza
  description: Gastronomie Pizza API Specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ingredients:
    get:
      description: Get the list of all ingredients
      operationId: getAll
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
        '500':
          description: Internal server error
    put:
      description: Add new ingredient
      operationId: add
      responses:
        '201':
          description: created with success

components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        unit:
          $ref: '#/components/schemas/Unit'
        prices:
          items:
            $ref: '#/components/schemas/Price'
        availableQuantity:
          type: number
        actualPrice:
          type: number

    Price:
      type: object
      properties:
        id:
          type: number
        price:
          type: number
        dateValue:
          type: string
          pattern: '^\d{2}-\d{2}-\d{2}$'
          example: "01-04-25"

    Stock:
      type: object
      properties:
        id:
          type: number
        quantityINOUT:
          $ref: '#/components/schemas/StockMovementType'
        dateOfMovement:
          type: string
          pattern: '^\d{2}-\d{2}-\d{2}$'
          example: "01-04-25"

    Unit:
      type: string
      enum:
        - G
        - L
        - U

    StockMovementType:
      type: string
      enum:
        - IN
        - OUT
